version: '3.9'
services:
  flipmart:
    image: mysql:8.0.32
    container_name: shop_flipmart
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
  redis:
    image: redis:7.0.9
    container_name: redisjava
    ports:
      - 6379:6379