server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/shop_flipmart
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update