server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/shop_flipmart
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update